apiVersion: v1
kind: Service
metadata:
  name: tapo-exporter
  namespace: monitoring
  labels:
    app: tapo-exporter
spec:
  selector:
    app: tapo-exporter
  ports:
    - name: metrics
      port: 9801
      targetPort: metrics
      protocol: TCP
