apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tapo-exporter
  namespace: monitoring
  labels:
    app: tapo-exporter
spec:
  endpoints:
    - interval: 15s
      scrapeTimeout: 10s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: tapo-exporter
