apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tapo-credentials
  namespace: monitoring
spec:
  vaultAuthRef: vault-auth
  mount: secret
  path: tapo
  type: kv-v2
  refreshAfter: 1h
  destination:
    name: tapo-credentials
    create: true
    overwrite: true
  hmacSecretData: true
